apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-a
  labels:
    app: aceest-fitness
    version: a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: a
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: a
    spec:
      containers:
        - name: aceest-fitness
          image: 9kiran/aceest_fitness:v1
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-b
  labels:
    app: aceest-fitness
    version: b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: b
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: b
    spec:
      containers:
        - name: aceest-fitness
          image: 9kiran/aceest_fitness:v2
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-ab-service
spec:
  type: LoadBalancer
  selector:
    app: aceest-fitness
  ports:
    - port: 80
      targetPort: 5000
